### ISSUE TITLE
Suggestion: Add an example to `list_all_serial_ports`

### ISSUE THREAD

**Issue by fvilante** [DjDeveloperr/deno_serial#2]
An example to list all serial ports present, is like a `hello word` example for this kind of lib. 

People should just type `deno run <address_of_the_example>` in their terminal and get to know if the lib can detect its own serial ports.

Normally if the lib pass this step, they believe it may be work in their project.

You should also add up above command line in the README.md so lib's lead can just copy and past in your terminal.

Note: I can pull request this change if necessary. Just let me know.

Thank you for write this amazing lib.

**Comment by DjDeveloperr** [comment]
Sounds good to me, PRs are welcome :)

FYI this library currently doesn't work on Linux and macOS. Only Windows implementation is there, but I do plan to work on supporting other platforms. Initial release will be made when it supports all these major platforms.

**Comment by DjDeveloperr** [comment]
Added the example
