### ISSUE TITLE
About support for others Operational Systems

### ISSUE THREAD

**Issue by fvilante** [DjDeveloperr/deno_serial#5]
Do you think it should be possible to call a Rust library from Deno using (using dlopen or something else) ?

Because we eventually could study to use the [rust serial ports lib](https://github.com/serialport/serialport-rs) and just make a bridge between deno and the rust lib. I don't know if this would be valid solution in Deno.

Do you know if this should works for deno?

I can build and test the rust side, eventually.

PS: It seems that the maintainer of the rust serial lib, is the [same](https://github.com/serialport) mantainer of the node.js serial-lib.

related: #3 https://github.com/DjDeveloperr/deno_serial/issues/2#issuecomment-1405507959

**Comment by DjDeveloperr** [comment]
It's definitely possible to call a Rust library from Deno using `dlopen`. Just need to make a C interface for it (using `extern "C" fn`s mostly).

It would work but my goal with this library was to build from scratch, using low-level OS APIs while also learning about them :) That also allows us to have zero third-party native dependencies.

**Comment by fvilante** [comment]
Nice!

Do this repository have a chat room so we can explore on this?

I may perform tests on the Windows side.

**Comment by DjDeveloperr** [comment]
I've made a channel on Discord server for this repo: https://discord.gg/5q5B23y8cM
