### ISSUE TITLE
Problems in loading this lib from Deno/x

### ISSUE THREAD

**Issue by fvilante** [DjDeveloperr/deno_serial#6]
The link in the ["try out" section](https://github.com/DjDeveloperr/deno_serial/blob/cb87eace1abece8286ffa9293ce01419b7826f49/README.md?plain=1#L20) of the readme.file is broken.

```powershell
╰─❯ deno run --unstable --allow-ffi https://deno.land/x/serialport@0.1.0/examples/print_ports.ts
error: Module not found "https://deno.land/x/serialport@0.1.0/examples/print_ports.ts".
```

I could not found any "serialport" lib in the Deno/X repository: https://deno.land/x?query=serialport

**Comment by DjDeveloperr** [comment]
As it is unfinished yet, I have not published a version on deno.land/x. I'll do it once all platforms have a working implementation. For now, you need to run/import from the repo directly: https://raw.githubusercontent.com/DjDeveloperr/deno_serial/main/examples/print_ports.ts

**Comment by fvilante** [comment]
Why not to put it clearly on the readme file?

**Comment by DjDeveloperr** [comment]
Okay I just added it to readme.

**Comment by fvilante** [comment]
Ok, tested and the link of the readme is working.
Clossing this issue
